@echo off
echo ========================================
echo  ServingSync POS - Windows .exe Builder
echo ========================================
echo.

REM Change to the directory where this .bat file is located
cd /d "%~dp0"

echo Current directory: %cd%
echo.

REM ─── Step 0: Configure mirrors to avoid "Failed to archive download files" ───
REM The #1 cause of electron-builder failing on Windows is that it can't
REM download winCodeSign / nsis / electron binaries from GitHub (slow or
REM blocked in many regions). These env vars redirect downloads to the
REM npmmirror.com CDN which is fast and reliable globally.
echo Step 0: Configuring download mirrors (fixes "Failed to archive" errors)...
set "ELECTRON_MIRROR=https://npmmirror.com/mirrors/electron/"
set "ELECTRON_BUILDER_BINARIES_MIRROR=https://npmmirror.com/mirrors/electron-builder-binaries/"
set "ELECTRON_CUSTOM_DIR={{ version }}"
set "SASS_BINARY_SITE=https://npmmirror.com/mirrors/node-sass"
set "NODE_MIRROR=https://npmmirror.com/mirrors/node/"
echo Mirrors configured.
echo.

REM ─── Step 1: Clean previous build output ───
echo Step 1: Cleaning previous build artifacts...
if exist "release" rmdir /s /q "release"
if exist ".next" rmdir /s /q ".next"
echo Cleaned.
echo.

echo Step 2: Installing dependencies...
call npm install
if %errorlevel% neq 0 (
    echo ERROR: npm install failed
    echo Make sure you have Node.js installed: https://nodejs.org
    pause
    exit /b 1
)

echo.
echo Step 3: Generating Windows .ico icon from SVG...
call node scripts/gen-icon.js
if %errorlevel% neq 0 (
    echo ERROR: Icon generation failed
    pause
    exit /b 1
)

echo.
echo Step 4: Generating Prisma client...
call npx prisma generate
if %errorlevel% neq 0 (
    echo ERROR: Prisma generate failed
    pause
    exit /b 1
)

echo.
echo Step 5: Building Next.js standalone...
call npm run build
if %errorlevel% neq 0 (
    echo ERROR: Next.js build failed
    pause
    exit /b 1
)

echo.
echo Step 6: Verifying standalone output...
if not exist ".next\standalone\server.js" (
    echo ERROR: .next\standalone\server.js not found
    echo The Next.js build may have failed silently. Check the output above.
    pause
    exit /b 1
)
if not exist ".next\standalone\public\sql-wasm.wasm" (
    echo WARNING: sql-wasm.wasm missing from standalone/public/
    echo Copying it manually...
    copy /Y "public\sql-wasm.wasm" ".next\standalone\public\sql-wasm.wasm" >nul 2>&1
)
if not exist ".next\standalone\public\sql-wasm-browser.wasm" (
    echo WARNING: sql-wasm-browser.wasm missing from standalone/public/
    echo Copying it manually...
    copy /Y "public\sql-wasm-browser.wasm" ".next\standalone\public\sql-wasm-browser.wasm" >nul 2>&1
)
echo Standalone output verified.
echo.

echo.
echo Step 7: Building Electron .exe installer...
echo (Using mirrors to avoid GitHub download failures)
call npx electron-builder --win --x64
if %errorlevel% neq 0 (
    echo.
    echo ========================================
    echo  ERROR: Electron build failed
    echo ========================================
    echo.
    echo Most likely cause: "Failed to archive download files"
    echo This means winCodeSign or nsis binaries could not be downloaded.
    echo.
    echo TRY THIS FIX:
    echo   1. Run fix-build-cache.bat (downloads binaries manually)
    echo   2. Then run build-exe.bat again
    echo.
    echo Or try the alternative method below...
    echo.
    echo Trying alternative method (electron-packager)...
    call npx electron-packager . "ServingSync POS" --platform=win32 --arch=x64 --overwrite --prune=true --out=release --ignore="upload|scripts|dev.log|server.log|\.env$|release"
    if %errorlevel% neq 0 (
        echo ERROR: Both build methods failed
        echo Please run fix-build-cache.bat first, then try again.
        pause
        exit /b 1
    )
)

echo.
echo ========================================
echo  BUILD COMPLETE!
echo ========================================
echo.
echo Your .exe is in the "release" folder.
echo   - "release\ServingSync POS Setup.exe"  (installer)
echo   - "release\win-unpacked\ServingSync POS.exe"  (portable)
echo.
echo NOTE: builder-effective-config.yaml is a normal debug log file
echo generated by electron-builder — it is NOT an error.
echo.
echo To run: Double-click "release\ServingSync POS Setup.exe"
echo.
echo First launch will ask for a license key.
echo Login: super@servingsync.com / admin123
echo.
pause
